language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
env:
  - RUST_TEST_THREADS=1
addons:
  apt:
    packages:
      - jackd
      - libjack-dev
      - libjack0
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
before_install:
  - jackd -r -ddummy -r44100 -p1024 &
script:
  - cargo test
