language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
env:
  - RUST_TEST_THREADS=1
addons:
  apt:
    packages:
      - jackd2
      - libjack-jackd2-dev
      - libjack-jackd2-0
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH
before_install:
  - jackd -v -r -ddummy -r44100 -p1024 &
script:
  - |
      cargo build &&
      cargo test
after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis-cargo coveralls --no-sudo --verify; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./kcov/build/src/kcov --verify --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/sqa_jack-*; fi
