[package]
name = "sqa-backend-test"
version = "0.1.0"
authors = ["eeeeeta <eeeeeta@users.noreply.github.com>"]

[dependencies]
sqa-backend = { path = "../sqa-backend" }
rmp-serde = "0.13"
serde = "1.0"
serde_derive = "1.0"
futures = "0.1"
tokio-core = "0.1"
